# Form implementation generated from reading ui file 'Ui_WinQSB.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from common import get_resource_path, load_stylesheet


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 561)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(950, 560))
        self.centralwidget.setMaximumSize(QtCore.QSize(950, 560))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_main = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_main.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
                                      "                                  stop:0 rgb(128, 94, 62), \n"
                                      "                                  stop:1 rgb(128, 94, 162));\n"
                                      "border-radius:28px;")
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_main.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_main.setSpacing(0)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.frame_head_ad = QtWidgets.QFrame(parent=self.frame_main)
        self.frame_head_ad.setStyleSheet("background:rgba(0, 0, 0, 0);\n"
                                         "border-radius:16px;")
        self.frame_head_ad.setObjectName("frame_head_ad")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_head_ad)
        self.horizontalLayout_3.setContentsMargins(24, 6, 24, 6)
        self.horizontalLayout_3.setSpacing(24)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_title = QtWidgets.QLabel(parent=self.frame_head_ad)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_title.setStyleSheet("color:rgb(255, 255, 255);")
        self.label_title.setWordWrap(False)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_3.addWidget(self.label_title)
        self.pushButton_bought = QtWidgets.QPushButton(parent=self.frame_head_ad)
        self.pushButton_bought.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButton_bought.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_bought.setStyleSheet("QPushButton{\n"
                                             "color:rgb(226, 226, 226);\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             "color:rgb(236, 236, 236);\n"
                                             "}\n"
                                             "QPushButton:pressed {\n"
                                             "color:rgb(255, 255, 255);\n"
                                             "}\n"
                                             "")
        self.pushButton_bought.setObjectName("pushButton_bought")
        self.horizontalLayout_3.addWidget(self.pushButton_bought)
        self.pushButton_close_5 = QtWidgets.QPushButton(parent=self.frame_head_ad)
        self.pushButton_close_5.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_close_5.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_5.setFont(font)
        self.pushButton_close_5.setStyleSheet("QPushButton{\n"
                                              "background-color: rgba(255, 255, 255, 0);\n"
                                              "}\n"
                                              "QPushButton:hover {\n"
                                              "background-color: rgba(255, 255, 255, 20);\n"
                                              "}\n"
                                              "QPushButton:pressed {\n"
                                              "background-color: rgba(255, 255, 255, 50);\n"
                                              "}\n"
                                              "")
        self.pushButton_close_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/close.svg')), QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        self.pushButton_close_5.setIcon(icon)
        self.pushButton_close_5.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_close_5.setObjectName("pushButton_close_5")
        self.horizontalLayout_3.addWidget(self.pushButton_close_5)
        self.horizontalLayout_3.setStretch(0, 2)
        self.verticalLayout_main.addWidget(self.frame_head_ad)
        self.widget_3 = QtWidgets.QWidget(parent=self.frame_main)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_3.setStyleSheet(".QWidget{\n"
                                    "background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
                                    "                                  stop:0 rgb(255, 247, 237), \n"
                                    "                                  stop:1 rgb(255, 255, 255));\n"
                                    "border-radius:24px;\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "}\n"
                                    
                                    "")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(18, 18, 18, 18)
        self.horizontalLayout_5.setSpacing(18)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_select = QtWidgets.QFrame(parent=self.widget_3)
        self.frame_select.setStyleSheet("background:rgba(0, 0, 0, 0);")
        self.frame_select.setObjectName("frame_select")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_select)
        self.horizontalLayout.setContentsMargins(9, 6, 9, 6)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_P4 = QtWidgets.QPushButton(parent=self.frame_select)
        self.pushButton_P4.setMinimumSize(QtCore.QSize(156, 115))
        self.pushButton_P4.setMaximumSize(QtCore.QSize(156, 115))
        self.pushButton_P4.setStyleSheet("QPushButton{\n"
                                         "    margin-right:3px;\n"
                                         "    margin-bottom:0px;\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    border: 1px solid rgba(120, 120, 120, 60);\n"
                                         "    border-radius:8px;\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                         "                                      stop:0 rgba(215, 184, 221, 40), \n"
                                         "                                      stop:1 rgba(255, 85, 127, 0));\n"
                                         "border: 2px solid rgb(216, 159, 91);\n"
                                         "}\n"
                                         "QPushButton:pressed {\n"
                                         "background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                         "                                      stop:0 rgba(215, 184, 221, 40), \n"
                                         "                                      stop:1 rgba(255, 85, 127, 0));\n"
                                         "border: 2px solid rgb(179, 128, 69);\n"
                                         "}\n"
                                         "")
        self.pushButton_P4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/4.9-click.png')), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.pushButton_P4.setIcon(icon1)
        self.pushButton_P4.setIconSize(QtCore.QSize(156, 115))
        self.pushButton_P4.setObjectName("pushButton_P4")
        self.horizontalLayout.addWidget(self.pushButton_P4)
        self.pushButton_P6 = QtWidgets.QPushButton(parent=self.frame_select)
        self.pushButton_P6.setMinimumSize(QtCore.QSize(156, 115))
        self.pushButton_P6.setMaximumSize(QtCore.QSize(156, 115))
        self.pushButton_P6.setStyleSheet("QPushButton{\n"
                                         "    margin-right:3px;\n"
                                         "    margin-bottom:0px;\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    border: 1px solid rgba(120, 120, 120, 60);\n"
                                         "    border-radius:8px;\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                         "                                      stop:0 rgba(128, 94, 162, 40), \n"
                                         "                                      stop:1 rgba(255, 85, 127, 0));\n"
                                         "border: 2px solid rgb(216, 159, 91);\n"
                                         "}\n"
                                         "QPushButton:pressed {\n"
                                         "background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                         "                                      stop:0 rgba(128, 94, 162, 40), \n"
                                         "                                      stop:1 rgba(255, 85, 127, 0));\n"
                                         "border: 2px solid rgb(179, 128, 69);\n"
                                         "}\n"
                                         "")
        self.pushButton_P6.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/6.9-UNclick.png')),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_P6.setIcon(icon2)
        self.pushButton_P6.setIconSize(QtCore.QSize(156, 115))
        self.pushButton_P6.setObjectName("pushButton_P6")
        self.horizontalLayout.addWidget(self.pushButton_P6)
        self.pushButton_P16 = QtWidgets.QPushButton(parent=self.frame_select)
        self.pushButton_P16.setMinimumSize(QtCore.QSize(156, 115))
        self.pushButton_P16.setMaximumSize(QtCore.QSize(156, 115))
        self.pushButton_P16.setStyleSheet("QPushButton{\n"
                                          "    margin-right:3px;\n"
                                          "    margin-bottom:0px;\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    border: 1px solid rgba(120, 120, 120, 60);\n"
                                          "    border-radius:8px;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                          "                                      stop:0 rgba(128, 94, 162, 40), \n"
                                          "                                      stop:1 rgba(255, 85, 127, 0));\n"
                                          "border: 2px solid rgb(216, 159, 91);\n"
                                          "}\n"
                                          "QPushButton:pressed {\n"
                                          "background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                          "                                      stop:0 rgba(128, 94, 162, 40), \n"
                                          "                                      stop:1 rgba(255, 85, 127, 0));\n"
                                          "border: 2px solid rgb(179, 128, 69);\n"
                                          "}\n"
                                          "")
        self.pushButton_P16.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/16.7-UNclick.png')),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_P16.setIcon(icon3)
        self.pushButton_P16.setIconSize(QtCore.QSize(156, 115))
        self.pushButton_P16.setObjectName("pushButton_P16")
        self.horizontalLayout.addWidget(self.pushButton_P16)
        self.pushButton_P19 = QtWidgets.QPushButton(parent=self.frame_select)
        self.pushButton_P19.setMinimumSize(QtCore.QSize(156, 115))
        self.pushButton_P19.setMaximumSize(QtCore.QSize(156, 115))
        self.pushButton_P19.setStyleSheet("QPushButton{\n"
                                          "    margin-right:3px;\n"
                                          "    margin-bottom:0px;\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    border: 1px solid rgba(120, 120, 120, 60);\n"
                                          "    border-radius:8px;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                          "                                      stop:0 rgba(128, 94, 162, 40), \n"
                                          "                                      stop:1 rgba(255, 85, 127, 0));\n"
                                          "border: 2px solid rgb(216, 159, 91);\n"
                                          "}\n"
                                          "QPushButton:pressed {\n"
                                          "background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                                          "                                      stop:0 rgba(128, 94, 162, 40), \n"
                                          "                                      stop:1 rgba(255, 85, 127, 0));\n"
                                          "border: 2px solid rgb(179, 128, 69);\n"
                                          "}\n"
                                          "")
        self.pushButton_P19.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/19.8-UNclick.png')),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_P19.setIcon(icon4)
        self.pushButton_P19.setIconSize(QtCore.QSize(156, 115))
        self.pushButton_P19.setObjectName("pushButton_P19")
        self.horizontalLayout.addWidget(self.pushButton_P19)
        self.verticalLayout_5.addWidget(self.frame_select)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(12, 0, -1, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_Produce = QtWidgets.QLabel(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Produce.setFont(font)
        self.label_Produce.setStyleSheet("background:rgba(0, 0, 0, 0);\n"
                                         "color:rgba(128, 127, 127, 255);")
        self.label_Produce.setObjectName("label_Produce")
        self.verticalLayout_4.addWidget(self.label_Produce)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.frame_code = QtWidgets.QFrame(parent=self.widget_3)
        self.frame_code.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
                                      "                                  stop:0 #fff1e4, \n"
                                      "                                  stop:1 #fff7e5);\n"
                                      "border-radius: 20px;")
        self.frame_code.setObjectName("frame_code")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_code)
        self.verticalLayout.setContentsMargins(0, 18, 0, 9)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.label_0 = QtWidgets.QLabel(parent=self.frame_code)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_0.setFont(font)
        self.label_0.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_0.setStyleSheet("background:rgba(0, 0, 0, 0);\n"
                                   "color:rgb(71, 30, 22);")
        self.label_0.setWordWrap(False)
        self.label_0.setObjectName("label_0")
        self.horizontalLayout_13.addWidget(self.label_0)
        self.label_identfy = QtWidgets.QLabel(parent=self.frame_code)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_identfy.setFont(font)
        self.label_identfy.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_identfy.setStyleSheet("background:rgba(0, 0, 0, 0);\n"
                                         "color:rgb(71, 30, 22);")
        self.label_identfy.setWordWrap(False)
        self.label_identfy.setObjectName("label_identfy")
        self.horizontalLayout_13.addWidget(self.label_identfy)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(139, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_PIN = QtWidgets.QLineEdit(parent=self.frame_code)
        self.lineEdit_PIN.setMinimumSize(QtCore.QSize(0, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_PIN.setFont(font)
        self.lineEdit_PIN.setStyleSheet("background:rgb(255, 255, 255);\n"
                                        "border-radius:4px;\n"
                                        "border: 1px solid rgba(120, 120, 120, 150);")
        self.lineEdit_PIN.setInputMask("")
        self.lineEdit_PIN.setText("")
        self.lineEdit_PIN.setObjectName("lineEdit_PIN")
        self.horizontalLayout_2.addWidget(self.lineEdit_PIN)
        self.pushButton_OK = QtWidgets.QPushButton(parent=self.frame_code)
        self.pushButton_OK.setMinimumSize(QtCore.QSize(102, 38))
        self.pushButton_OK.setMaximumSize(QtCore.QSize(102, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_OK.setFont(font)
        self.pushButton_OK.setStyleSheet("QPushButton {\n"
                                         "    background: rgb(215, 184, 121);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    border-radius: 4px;\n"
                                         "    transition: background 0.3s, transform 0.2s;\n"
                                         "}\n"
                                         
                                         "QPushButton:hover {\n"
                                         "    background: rgb(235, 204, 141);\n"
                                         "}\n"
                                         
                                         "QPushButton:pressed {\n"
                                         "    background: rgb(195, 164, 101);\n"
                                         "    transform: translateY(2px);\n"
                                         "}")
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.horizontalLayout_2.addWidget(self.pushButton_OK)
        self.label_error = QtWidgets.QLabel(parent=self.frame_code)
        self.label_error.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("background:rgba(0, 0, 0, 0);\n"
                                       "color:rgb(255, 0, 0);")
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_2.addWidget(self.label_error)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout_5.addWidget(self.frame_code)
        self.frame_bottom = QtWidgets.QFrame(parent=self.widget_3)
        self.frame_bottom.setStyleSheet("background:rgba(0, 0, 0, 0);")
        self.frame_bottom.setObjectName("frame_bottom")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_bottom)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.frame_bottom)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_jiaocheng = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.pushButton_jiaocheng.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_jiaocheng.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_jiaocheng.setFont(font)
        self.pushButton_jiaocheng.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_jiaocheng.setStyleSheet("QPushButton {\n"
                                                "    background: rgb(215, 184, 121);\n"
                                                "    color: rgb(255, 255, 255);\n"
                                                "    border-radius: 4px;\n"
                                                "    transition: background 0.3s, transform 0.2s;\n"
                                                "}\n"
                                                
                                                "QPushButton:hover {\n"
                                                "    background: rgb(235, 204, 141);\n"
                                                "}\n"
                                                
                                                "QPushButton:pressed {\n"
                                                "    background: rgb(195, 164, 101);\n"
                                                "    transform: translateY(2px);\n"
                                                "}")
        self.pushButton_jiaocheng.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/安装教程.svg')), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.pushButton_jiaocheng.setIcon(icon5)
        self.pushButton_jiaocheng.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_jiaocheng.setObjectName("pushButton_jiaocheng")
        self.horizontalLayout_6.addWidget(self.pushButton_jiaocheng)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_bottom)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_5.setStyleSheet("")
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_bottom)
        self.label_6.setStyleSheet("background:rgba(0, 0, 0, 0);\n"
                                   "color:rgba(128, 127, 127, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.verticalLayout_6.setStretch(0, 4)
        self.verticalLayout_6.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_yuancheng = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.pushButton_yuancheng.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_yuancheng.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_yuancheng.setFont(font)
        self.pushButton_yuancheng.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_yuancheng.setStyleSheet("QPushButton {\n"
                                                "    background: rgb(215, 184, 121);\n"
                                                "    color: rgb(255, 255, 255);\n"
                                                "    border-radius: 4px;\n"
                                                "    transition: background 0.3s, transform 0.2s;\n"
                                                "}\n"
                                                
                                                "QPushButton:hover {\n"
                                                "    background: rgb(235, 204, 141);\n"
                                                "}\n"
                                                
                                                "QPushButton:pressed {\n"
                                                "    background: rgb(195, 164, 101);\n"
                                                "    transform: translateY(2px);\n"
                                                "}")
        self.pushButton_yuancheng.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/远程服务.svg')), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.pushButton_yuancheng.setIcon(icon6)
        self.pushButton_yuancheng.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_yuancheng.setObjectName("pushButton_yuancheng")
        self.horizontalLayout_7.addWidget(self.pushButton_yuancheng)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.label_13 = QtWidgets.QLabel(parent=self.frame_bottom)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_13.setStyleSheet("")
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_bottom)
        self.label_14.setStyleSheet("background:rgba(0, 0, 0, 0);\n"
                                    "color:rgba(128, 127, 127, 255);")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.verticalLayout_10.setStretch(0, 4)
        self.verticalLayout_10.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_tuikuan = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.pushButton_tuikuan.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_tuikuan.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_tuikuan.setFont(font)
        self.pushButton_tuikuan.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_tuikuan.setStyleSheet("QPushButton {\n"
                                              "    background: rgb(215, 184, 121);\n"
                                              "    color: rgb(255, 255, 255);\n"
                                              "    border-radius: 4px;\n"
                                              "    transition: background 0.3s, transform 0.2s;\n"
                                              "}\n"
                                              
                                              "QPushButton:hover {\n"
                                              "    background: rgb(235, 204, 141);\n"
                                              "}\n"
                                              
                                              "QPushButton:pressed {\n"
                                              "    background: rgb(195, 164, 101);\n"
                                              "    transform: translateY(2px);\n"
                                              "}")
        self.pushButton_tuikuan.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/退款.svg')), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.pushButton_tuikuan.setIcon(icon7)
        self.pushButton_tuikuan.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_tuikuan.setObjectName("pushButton_tuikuan")
        self.horizontalLayout_8.addWidget(self.pushButton_tuikuan)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_bottom)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_15.setStyleSheet("")
        self.label_15.setWordWrap(False)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_11.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_bottom)
        self.label_16.setStyleSheet("background:rgba(0, 0, 0, 0);\n"
                                    "color:rgba(128, 127, 127, 255);")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_11.addWidget(self.label_16)
        self.verticalLayout_11.setStretch(0, 4)
        self.verticalLayout_11.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_5.addWidget(self.frame_bottom)
        self.verticalLayout_5.setStretch(0, 4)
        self.verticalLayout_5.setStretch(2, 3)
        self.verticalLayout_5.setStretch(3, 4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.frame_right_pay = QtWidgets.QFrame(parent=self.widget_3)
        self.frame_right_pay.setStyleSheet("background:rgb(248, 248, 248);")
        self.frame_right_pay.setObjectName("frame_right_pay")
        self.verticalLayout_pay = QtWidgets.QVBoxLayout(self.frame_right_pay)
        self.verticalLayout_pay.setContentsMargins(24, 12, 24, 0)
        self.verticalLayout_pay.setSpacing(4)
        self.verticalLayout_pay.setObjectName("verticalLayout_pay")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_Price = QtWidgets.QLabel(parent=self.frame_right_pay)
        font = QtGui.QFont()
        font.setPointSize(34)
        font.setBold(True)
        self.label_Price.setFont(font)
        self.label_Price.setStyleSheet("background:rgba(0, 0, 0, 0);\n"
                                       "color:rgb(71, 30, 22);")
        self.label_Price.setObjectName("label_Price")
        self.horizontalLayout_12.addWidget(self.label_Price)
        self.verticalLayout_pay.addLayout(self.horizontalLayout_12)
        self.verticalFrame_4 = QtWidgets.QFrame(parent=self.frame_right_pay)
        self.verticalFrame_4.setMaximumSize(QtCore.QSize(170, 16777215))
        self.verticalFrame_4.setStyleSheet("background:rgb(255, 255, 255);\n"
                                           "border-radius:14px;")
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_head_ad_2 = QtWidgets.QFrame(parent=self.verticalFrame_4)
        self.frame_head_ad_2.setMinimumSize(QtCore.QSize(170, 170))
        self.frame_head_ad_2.setMaximumSize(QtCore.QSize(170, 170))
        self.frame_head_ad_2.setStyleSheet("background:rgba(0, 0, 0, 0);\n"
                                           "border-radius:16px;")
        self.frame_head_ad_2.setObjectName("frame_head_ad_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_head_ad_2)
        self.horizontalLayout_11.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_QRcode = QtWidgets.QPushButton(parent=self.frame_head_ad_2)
        self.pushButton_QRcode.setMinimumSize(QtCore.QSize(150, 150))
        self.pushButton_QRcode.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_QRcode.setFont(font)
        self.pushButton_QRcode.setStyleSheet("QPushButton{\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "    border-radius:2px;\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             
                                             "}\n"
                                             "QPushButton:pressed {\n"
                                             
                                             "}\n"
                                             "")
        self.pushButton_QRcode.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(get_resource_path('resources/img/4.9.jpg')), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.pushButton_QRcode.setIcon(icon8)
        self.pushButton_QRcode.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_QRcode.setObjectName("pushButton_QRcode")
        self.horizontalLayout_11.addWidget(self.pushButton_QRcode)
        self.verticalLayout_14.addWidget(self.frame_head_ad_2)
        self.verticalLayout_14.setStretch(0, 3)
        self.verticalLayout_pay.addWidget(self.verticalFrame_4)
        self.frame_option_2 = QtWidgets.QFrame(parent=self.frame_right_pay)
        self.frame_option_2.setStyleSheet("background:rgb(248, 248, 248);\n"
                                          "border-radius:0px;")
        self.frame_option_2.setObjectName("frame_option_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_option_2)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_bought_2 = QtWidgets.QPushButton(parent=self.frame_option_2)
        self.pushButton_bought_2.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_bought_2.setMaximumSize(QtCore.QSize(130, 30))
        self.pushButton_bought_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_bought_2.setStyleSheet(load_stylesheet("Confirm_Payment.css"))
        self.pushButton_bought_2.setObjectName("pushButton_bought_2")
        self.horizontalLayout_14.addWidget(self.pushButton_bought_2)
        self.verticalLayout_pay.addWidget(self.frame_option_2)
        self.label_tips = QtWidgets.QLabel(parent=self.frame_right_pay)
        self.label_tips.setStyleSheet("color:rgba(128, 127, 127, 255);")
        self.label_tips.setObjectName("label_tips")
        self.verticalLayout_pay.addWidget(self.label_tips)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_pay.addItem(spacerItem2)
        self.verticalLayout_pay.setStretch(0, 1)
        self.verticalLayout_pay.setStretch(1, 2)
        self.verticalLayout_pay.setStretch(4, 1)
        self.horizontalLayout_5.addWidget(self.frame_right_pay)
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_main.addWidget(self.widget_3)
        self.verticalLayout_main.setStretch(0, 1)
        self.verticalLayout_main.setStretch(1, 9)
        self.verticalLayout_2.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow",
                                            "<html><head/><body><p align=\"justify\">WinQSB "
                                            "安装程序将在输入安装秘钥后继续</p></body></html>"))
        self.pushButton_bought.setText(_translate("MainWindow", "我已购买"))
        self.label_Produce.setText(_translate("MainWindow", "极致性价比，可使用3个月，安装成功后无任何售后"))
        self.label_0.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">随机识别码：</p></body></html>"))
        self.label_identfy.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">123456</p></body></html>"))
        self.lineEdit_PIN.setPlaceholderText(_translate("MainWindow", "请输入安装秘钥"))
        self.pushButton_OK.setText(_translate("MainWindow", "安装"))
        self.label.setText(_translate("MainWindow", "安装尊享权益"))
        self.label_5.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">请阅读安装教程</p></body></html>"))
        self.label_6.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\">请阅读安装教程，根据教程操作</p></body></html>"))
        self.label_13.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">免费远程服务</p></body></html>"))
        self.label_14.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">我们均提供免费远程服务</p></body></html>"))
        self.label_15.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">安装失败包退款</p></body></html>"))
        self.label_16.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">安装失败，退还全款</p></body></html>"))
        self.label_Price.setText(_translate("MainWindow",
                                            "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">￥</span><span style=\" font-size:28pt;\">4.9</span></p></body></html>"))
        self.pushButton_bought_2.setText(_translate("MainWindow", "我已购买"))
        self.label_tips.setText(_translate("MainWindow",
                                           "<html><head/><body><p align=\"center\">如已支付请点击 我已购买</p></body></html>"))
